version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: friday
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: stripe
    versions:
    - 8.140.0
